### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Tiliavir** [seanlane/gochowdown#12]
Have you considered supporting other languages?
I don't know hugos approach for internationalization but I saw its possible ...

**Comment by seanlane** [comment]
Hugo actually does have quite a bit of support in this regard (see https://gohugo.io/content-management/multilingual/), but it's not something I'm very familiar with myself, and I don't have any time in the immediate future to look into this. I'll keep the issue open though, and any pull requests would be welcome.

**Comment by hed854** [comment]
Hi, I added basic i18n support in #15 using the Hugo doc you referred to. It should be easy to add more language files using the same technique :smiley:

**Comment by seanlane** [comment]
Merged in #15
