### ISSUE TITLE
Pagination on front page ?

### ISSUE THREAD

**Issue by CyberHippo** [seanlane/gochowdown#16]
Hi, 
Does the pagination only apply to the components or also to the recipes shown on the front page ? 

PS : Thanks for all the great work on this theme !

**Comment by seanlane** [comment]
As it's currently implemented, it doesn't currently paginate the recipes, which can be cumbersome if you have lots of recipes. will leave this open, and mark it as help wanted.

**Comment by CyberHippo** [comment]
switched to gatbsyjs
