### ISSUE TITLE
Recipes on the sample home page

### ISSUE THREAD

**Issue by mroswell** [seanlane/gochowdown#7]
Would be great if https://themes.gohugo.io//theme/gochowdown/ showed some sample recipes to inspire confidence in adopting the theme. I don't know if this is related to issue #2....

**Comment by seanlane** [comment]
There were, at one time, recipes. I'll have to figure out to where they disappeared. I believe I need to update the theme on the gohugo website, since there was a breaking change sometime in the past. thanks for making an issue about it.

**Comment by seanlane** [comment]
The mystery is solved, they changed the demo generation process to not use custom content unless the theme is specifically allowed to do so. I'll close this once this pull request is accepted: https://github.com/gohugoio/hugoThemes/pull/893
