### ISSUE TITLE
Hugo Theme Demo - Categories Link goes to 404 page

### ISSUE THREAD

**Issue by damien1** [seanlane/gochowdown#8]
From the Demo ... https://themes.gohugo.io/theme/gochowdown/ when you click on Categories it goes to 404 page ...

https://themes.gohugo.io//theme/gochowdown/category/

**Comment by seanlane** [comment]
The demo generation process was changed, this should be fixed once this pull request is accepted: https://github.com/gohugoio/hugoThemes/pull/893. Thanks for making the issue.
